version: "3"

services:
    backend:
        build:
            context: ./backend
        depends_on:
            - mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_username
            MONGO_INITDB_ROOT_PASSWORD: mongo_password
            JWT_TOKEN_SECRET: "CDg7QAHA6KkmNsLpUTa9LyeHgLgENX3FLNrqTRBQDUbQuZgNzVYdqpDSUhKMuv58Y7aQ7m"
        hostname: backend
        image: universidad:desix-proyecto-final-backend
        ports:
            - "4000:4000"
        volumes:
            - "./backend/:/code/backend/"
            
    frontend:
        build:
            context: ./frontend
        depends_on:
            - backend
        hostname: frontend
        image: universidad:desix-proyecto-final-frontend
        ports:
            - "3000:3000"
        volumes:
            - "./frontend/:/code/frontend/"
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo_username
            MONGO_INITDB_ROOT_PASSWORD: mongo_password
        hostname: mongo
        volumes:
            - "./db:/data/db"
        ports:
            - "27017:27017"
